MONGODB_PROTOCOL = 'mongodb'
MONGO_INITDB_ROOT_USERNAME = 'mongodbuser'
MONGO_INITDB_ROOT_PASSWORD = 'your_mongodb_root_password'
MONGO_INITDB_DATABASE = 'chickiedb'
MONGODB_USERNAME = 'chickie'
MONGODB_PASSWORD = 'mongo_password'
MONGODB_HOST_NAME = 'localhost'
MONGODB_DATA_DIR = '/data/db'
MONDODB_LOG_DIR = '/dev/null'
MONGODB_PORT = '27017'
MONGODB_DATABASENAME = 'chickie'