[default]
POSTGRES_USERNAME = 'postgres'
POSTGRES_PASSWORD = 'Senha123456'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = 5432
POSTGRES_DATABASE_DEV = 'dev'

AUTH_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

SECRET_KEY = '39e3d48a93776226c9e01638d0b0e651b2a8038c869d6f9c7b0af724946e4965'

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD='gjn87/W35ti_8k0iq4Qmjz=mJ.qByt124mg8jev'

RABBITMQ_EXCHANGE = 'chickie'
RABBITMQ_HOST = 'localhost'
RABBITMQ_QUEUE = 'chickie'
RABBITMQ_PORT = '5672'
RABBITMQ_DEFAULT_USER = 'admin'
RABBITMQ_DEFAULT_PASS = "senha123"
RABBITMQ_ROUTING_KEY = 'chickie'
RABBITMQ_EXCHANGE_NAME = 'amq.direct'

[dev]
POSTGRES_DATABASE_DEV = 'dev'

[prod]
POSTGRES_DATABASE_PROD = 'chickie'
