[default]
CACHE_DEFAULT_TIMEOUT = 1800
MODE = 'LOCAL'

LOJA_NOME = "Loja Chickie"
LOJA_USERNAME = "chickie"
LOJA_TELEFONE = "2133333333"
LOJA_CELULAR = "21999999999"
LOJA_SENHA = "123123"
LOJA_EMAIL = "loja@chickie.com"

[dev]
MODE = 'DEV'
LOG_LEVEL = "DEBUG"

[prod]
MODE = 'PROD'
LOG_LEVEL = "INFO"
