version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ~/volumes/flask-sqlalchemy-postgres:/var/lib/postgresql/data
    env_file:
      - infra.secrets.toml
    ports:
      - "5432:5432"
  
  cache:
    image: redis
    restart: always
    env_file:
      - infra.secrets.toml
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  postgres-data: