version: '3'

services:
  database:
    image: postgres
    volumes:
      - ~/volumes/flask-sqlalchemy-postgres:/var/lib/postgresql/data
    env_file:
      - infra.secrets.toml
    ports:
      - "5432:5432"
  
  cache:
    image: redis
    restart: always
    env_file:
      - infra.secrets.toml
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - cache:/data
      - ./config/redis.secrets.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  cache:
  postgres-data: