POSTGRES_DATABASE = 'dev'
POSTGRES_USERNAME = 'postgres'
POSTGRES_PASSWORD = 'Senha123456'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = 5432

FLASK_SECRET_KEY = '9Yw3meanH42Kj6k5J2tN1fr6wfmDNBBWRdkcED1Uh9vwXgAatplan3ZE1BGYgZLSOeM'
SECURITY_KEY = 'KTd3q8aD-X1YmHki-JTzmaMsOrfPSoTIdSGaOnWLNdI='


REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD='gjn87/W35ti_8k0iq4Qmjz=mJ.qByt124mg8jev'